services:
  - type: web
    name: meteosarria-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: CACHE_TYPE
        value: simple
      - key: CACHE_DEFAULT_TIMEOUT
        value: 86400
      - key: CACHE_KEY_PREFIX
        value: meteosarria_prod_
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
    healthCheckPath: /api/dashboard/test
    autoDeploy: true 